# Generated by Django 5.2.2 on 2025-06-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL being reported as suspicious', max_length=500, verbose_name='Suspicious URL')),
                ('description', models.TextField(help_text='Detailed explanation of why this URL is suspicious', verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the report review', max_length=10, verbose_name='Review Status')),
                ('reported_date', models.DateTimeField(auto_now_add=True, help_text='When the URL was reported', verbose_name='Report Date')),
                ('reviewed_date', models.DateTimeField(blank=True, help_text='When the report was reviewed', null=True, verbose_name='Review Date')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('user', models.ForeignKey(help_text='User who reported the URL', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'verbose_name': 'URL Report',
                'verbose_name_plural': 'URL Reports',
                'ordering': ['-reported_date'],
            },
        ),
        migrations.CreateModel(
            name='URLScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL that was scanned for phishing', max_length=500, verbose_name='URL')),
                ('is_phishing', models.BooleanField(help_text='Whether the URL was identified as a phishing attempt', verbose_name='Is Phishing')),
                ('scan_date', models.DateTimeField(auto_now_add=True, help_text='When the scan was performed', verbose_name='Scan Date')),
                ('features', models.JSONField(blank=True, help_text='Extracted features used for phishing detection', null=True, verbose_name='URL Features')),
                ('confidence_score', models.FloatField(blank=True, help_text="Model's confidence in the prediction (0-1)", null=True, verbose_name='Confidence Score')),
                ('user', models.ForeignKey(help_text='User who performed the scan', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Scanned by')),
            ],
            options={
                'verbose_name': 'URL Scan',
                'verbose_name_plural': 'URL Scans',
                'ordering': ['-scan_date'],
            },
        ),
    ]
