# Generated by Django 5.2.2 on 2025-06-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded')], default='new', max_length=20),
        ),
    ]
