# Generated by Django 5.2.2 on 2025-06-08 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_replied_at_contact_replied_by_contact_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the URL was reported', verbose_name='Report Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the report review', max_length=10, verbose_name='Review Status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='url',
            field=models.URLField(db_index=True, help_text='The URL being reported as suspicious', max_length=500, verbose_name='Suspicious URL'),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='confidence_score',
            field=models.FloatField(blank=True, db_index=True, help_text="Model's confidence in the prediction (0-1)", null=True, verbose_name='Confidence Score'),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='is_phishing',
            field=models.BooleanField(db_index=True, help_text='Whether the URL was identified as a phishing attempt', verbose_name='Is Phishing'),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='scan_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the scan was performed', verbose_name='Scan Date'),
        ),
        migrations.AlterField(
            model_name='urlscan',
            name='url',
            field=models.URLField(db_index=True, help_text='The URL that was scanned for phishing', max_length=500, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user', '-reported_date'], name='core_report_user_id_e46f34_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-reported_date'], name='core_report_status_698990_idx'),
        ),
        migrations.AddIndex(
            model_name='urlscan',
            index=models.Index(fields=['user', '-scan_date'], name='core_urlsca_user_id_5a9e24_idx'),
        ),
        migrations.AddIndex(
            model_name='urlscan',
            index=models.Index(fields=['is_phishing', '-scan_date'], name='core_urlsca_is_phis_e19999_idx'),
        ),
    ]
